server:
  port: 8082

application:
  audience: https://spring-auth-zero/
  client-origin-url: http://localhost:3000

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-25mbthy4.us.auth0.com/